### ISSUE TITLE
Couldn't use Compose V3.

### ISSUE THREAD

**Issue by Trevo525** [djfdyuruiry/red-discord-server-docker#1]
I couldn't get it to run with Version 3 for some reason. I changed the version to 3.3 and it worked. I included the error it threw. I chose 3.3 because it was the example so I figured it was worth a try but It might just be a 'me problem'. :-P

`ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid top-level property "secrets". Valid top-level sections for this Compose file are: version, services, networks, volumes, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Unsupported config option for services.red: 'secrets'`

**Comment by djfdyuruiry** [comment]
Cheers for the find - updated this now to point to at least 3.3, think the secrets block was causing the issue when using 3.0
